layout_spectrum: 0.8781362
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.9714646
  brandStrength: 0.4157706
  lightness: 0.8727093
  brandColors:
    - '#FBFDEF'
    - '#242520'
    - '#C5D5CB'
    - '#7496A2'
    - '#235878'
  rhythmicContrast: 0.8888889
typography_spectrum: 0.09139785
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: William Miller
